// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/accounts" | "/dashboard/accounts/[id]" | "/dashboard/accounts/[id]/edit" | "/dashboard/accounts/new" | "/dashboard/activity" | "/dashboard/contacts" | "/dashboard/contacts/[id]" | "/dashboard/contacts/[id]/edit" | "/dashboard/contacts/new" | "/dashboard/customers" | "/dashboard/customers/accounts" | "/dashboard/customers/accounts/[id]" | "/dashboard/customers/accounts/[id]/edit" | "/dashboard/customers/accounts/new" | "/dashboard/customers/contacts" | "/dashboard/customers/contacts/[id]" | "/dashboard/customers/contacts/[id]/edit" | "/dashboard/customers/contacts/new" | "/dashboard/deals" | "/dashboard/deals/[id]" | "/dashboard/deals/new" | "/dashboard/import" | "/dashboard/import/[id]" | "/dashboard/import/history" | "/dashboard/leads" | "/dashboard/leads/[id]" | "/dashboard/leads/[id]/edit" | "/dashboard/leads/new" | "/dashboard/settings" | "/dashboard/settings/activity" | "/dashboard/settings/audit-log" | "/dashboard/settings/imports" | "/dashboard/settings/imports/[id]" | "/dashboard/settings/imports/history" | "/dashboard/tasks" | "/demo" | "/invite/[token]" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]"
type AppRouteHandlerRoutes = "/api/demo-login" | "/api/health" | "/api/imports" | "/api/imports/[id]" | "/api/imports/[id]/confirm" | "/api/imports/[id]/rejected" | "/api/imports/templates/[entityType]" | "/api/leads/export" | "/api/testing/e2e/notifications" | "/api/testing/e2e/reset"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/dashboard/customers" | "/dashboard/settings"
type RedirectRoutes = "/dashboard/accounts" | "/dashboard/accounts/[[...path]]" | "/dashboard/activity" | "/dashboard/contacts" | "/dashboard/contacts/[[...path]]" | "/dashboard/import/[id]" | "/dashboard/import/history"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/demo-login": {}
  "/api/health": {}
  "/api/imports": {}
  "/api/imports/[id]": { "id": string; }
  "/api/imports/[id]/confirm": { "id": string; }
  "/api/imports/[id]/rejected": { "id": string; }
  "/api/imports/templates/[entityType]": { "entityType": string; }
  "/api/leads/export": {}
  "/api/testing/e2e/notifications": {}
  "/api/testing/e2e/reset": {}
  "/dashboard": {}
  "/dashboard/accounts": {}
  "/dashboard/accounts/[[...path]]": { "path"?: string[]; }
  "/dashboard/accounts/[id]": { "id": string; }
  "/dashboard/accounts/[id]/edit": { "id": string; }
  "/dashboard/accounts/new": {}
  "/dashboard/activity": {}
  "/dashboard/contacts": {}
  "/dashboard/contacts/[[...path]]": { "path"?: string[]; }
  "/dashboard/contacts/[id]": { "id": string; }
  "/dashboard/contacts/[id]/edit": { "id": string; }
  "/dashboard/contacts/new": {}
  "/dashboard/customers": {}
  "/dashboard/customers/accounts": {}
  "/dashboard/customers/accounts/[id]": { "id": string; }
  "/dashboard/customers/accounts/[id]/edit": { "id": string; }
  "/dashboard/customers/accounts/new": {}
  "/dashboard/customers/contacts": {}
  "/dashboard/customers/contacts/[id]": { "id": string; }
  "/dashboard/customers/contacts/[id]/edit": { "id": string; }
  "/dashboard/customers/contacts/new": {}
  "/dashboard/deals": {}
  "/dashboard/deals/[id]": { "id": string; }
  "/dashboard/deals/new": {}
  "/dashboard/import": {}
  "/dashboard/import/[id]": { "id": string; }
  "/dashboard/import/history": {}
  "/dashboard/leads": {}
  "/dashboard/leads/[id]": { "id": string; }
  "/dashboard/leads/[id]/edit": { "id": string; }
  "/dashboard/leads/new": {}
  "/dashboard/settings": {}
  "/dashboard/settings/activity": {}
  "/dashboard/settings/audit-log": {}
  "/dashboard/settings/imports": {}
  "/dashboard/settings/imports/[id]": { "id": string; }
  "/dashboard/settings/imports/history": {}
  "/dashboard/tasks": {}
  "/demo": {}
  "/invite/[token]": { "token": string; }
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/dashboard/customers": never
  "/dashboard/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
