var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/imports/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__10xuo_6._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_213iqqr._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/lib_arcjet_ts_1tgo8we._.js")
R.c("server/chunks/_1hymn87._.js")
R.c("server/chunks/_124pzkb._.js")
R.c("server/chunks/_1p_mgx1._.js")
R.c("server/chunks/_next-internal_server_app_api_imports_[id]_route_actions_0k72lg_.js")
R.m(190561)
module.exports=R.m(190561).exports
