"use client";
import { useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createDealAction } from "@/app/dashboard/crm-actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DEAL_CURRENCIES, DEAL_STAGE_LABELS, DEAL_STAGES } from "@/lib/constants/crm";
import type { DealFormValues } from "@/lib/validations/deal";
type Option = { id: string; label: string };
export function DealForm({ selectors }: { selectors: { accounts: Option[]; contacts: Option[]; leads: Option[] } }) { const router = useRouter(); const [pending, startTransition] = useTransition(); return <form className="rounded-3xl border bg-background p-5 shadow-sm sm:p-6" action={(data) => startTransition(async () => { const raw = Object.fromEntries(data); const none = (value: FormDataEntryValue | undefined) => value === "none" ? undefined : value; const result = await createDealAction({ ...raw, accountId: none(raw.accountId), contactId: none(raw.contactId), leadId: none(raw.leadId) } as DealFormValues); if (!result.success) { toast.error(result.message); return; } toast.success(result.message); router.push(`/dashboard/deals/${result.id}`); router.refresh(); })}><div className="grid gap-5 md:grid-cols-2"><div className="md:col-span-2"><Label htmlFor="name">Deal name *</Label><Input name="name" id="name" required minLength={2} className="mt-2" placeholder="Website redesign package" /></div><div><Label>Stage</Label><Select name="stage" defaultValue="new"><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{DEAL_STAGES.map((stage) => <SelectItem key={stage} value={stage}>{DEAL_STAGE_LABELS[stage]}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="value">Value *</Label><Input name="value" id="value" type="number" min="0" step="0.01" defaultValue="0" className="mt-2" /></div><div><Label>Currency</Label><Select name="currency" defaultValue="USD"><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{DEAL_CURRENCIES.map((currency) => <SelectItem key={currency} value={currency}>{currency}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="probability">Probability</Label><Input name="probability" id="probability" type="number" min="0" max="100" defaultValue="10" className="mt-2" /></div><div><Label htmlFor="expectedCloseDate">Expected close</Label><Input name="expectedCloseDate" id="expectedCloseDate" type="date" className="mt-2" /></div><div><Label htmlFor="lostReason">Lost reason</Label><Input name="lostReason" id="lostReason" className="mt-2" /></div>{(["accountId", "contactId", "leadId"] as const).map((field) => <div key={field}><Label>{field === "accountId" ? "Account" : field === "contactId" ? "Contact" : "Lead"}</Label><Select name={field} defaultValue="none"><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No linked record</SelectItem>{selectors[field === "accountId" ? "accounts" : field === "contactId" ? "contacts" : "leads"].map((option) => <SelectItem key={option.id} value={option.id}>{option.label}</SelectItem>)}</SelectContent></Select></div>)}</div><div className="mt-6 flex justify-end gap-3 border-t pt-5"><Button type="button" variant="outline" onClick={() => router.back()} disabled={pending}>Cancel</Button><Button disabled={pending}>{pending ? "Creating…" : "Create deal"}</Button></div></form>; }
