"use client";
import { useState, useTransition } from "react";
import { DndContext, KeyboardSensor, PointerSensor, useDraggable, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import Link from "next/link";
import { AlertTriangle, Calendar, GripVertical, UserRound } from "lucide-react";
import { toast } from "sonner";
import { moveDealAction } from "@/app/dashboard/crm-actions";
import type { PipelineDeal } from "@/app/dashboard/deals/queries";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { DEAL_STAGE_LABELS, DEAL_STAGES, type DealStage } from "@/lib/constants/crm";
import { formatCurrencyFromCents } from "@/lib/revenue";

type Board = Record<DealStage, PipelineDeal[]>;
const isOverdue = (value: string | null, stage: DealStage) => Boolean(value && !["won", "lost"].includes(stage) && new Date(value).getTime() < Date.now());
function Column({ stage, children, total }: { stage: DealStage; children: React.ReactNode; total: { count: number; valueCents: number } }) { const { setNodeRef, isOver } = useDroppable({ id: stage }); return <section ref={setNodeRef} className={`flex w-80 shrink-0 flex-col rounded-3xl border bg-muted/20 transition-colors ${isOver ? "border-primary bg-primary/5" : ""}`}><header className="border-b px-4 py-4"><div className="flex items-center justify-between"><h2 className="font-semibold">{DEAL_STAGE_LABELS[stage]}</h2><span className="rounded-full bg-background px-2 py-0.5 text-xs text-muted-foreground">{total.count}</span></div><p className="mt-1 text-sm font-medium text-muted-foreground">{formatCurrencyFromCents(total.valueCents, "USD")}</p></header><div className="min-h-32 space-y-3 p-3">{children}</div></section>; }
function DealCard({ deal, readOnly, move }: { deal: PipelineDeal; readOnly: boolean; move: (deal: PipelineDeal, stage: DealStage, reason?: string) => void }) { const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: deal.id, disabled: readOnly }); const [selectedStage, setSelectedStage] = useState<DealStage>(deal.stage); return <article ref={setNodeRef} style={{ transform: CSS.Translate.toString(transform) }} className={`rounded-2xl border bg-background p-3 shadow-sm ${isDragging ? "opacity-50 shadow-lg" : ""}`}><div className="flex gap-2"><button type="button" aria-label={`Drag ${deal.name}`} className="mt-0.5 cursor-grab touch-none text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" {...attributes} {...listeners}><GripVertical className="h-4 w-4" /></button><div className="min-w-0 flex-1"><Link href={`/dashboard/deals/${deal.id}`} className="line-clamp-2 font-semibold hover:text-primary">{deal.name}</Link><p className="mt-1 truncate text-sm text-muted-foreground">{deal.accountName ?? deal.contactName ?? deal.leadName ?? "No linked relationship"}</p></div></div><div className="mt-3 flex items-end justify-between gap-2"><div><p className="font-semibold">{formatCurrencyFromCents(deal.valueCents, deal.currency)}</p><p className="text-xs text-muted-foreground">{deal.probability}% likely</p></div>{deal.expectedCloseAt ? <span className={`inline-flex items-center gap-1 text-xs ${isOverdue(deal.expectedCloseAt, deal.stage) ? "font-semibold text-destructive" : "text-muted-foreground"}`}><Calendar className="h-3 w-3" />{new Date(deal.expectedCloseAt).toLocaleDateString()}</span> : null}</div>{deal.ownerUserId ? <p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><UserRound className="h-3 w-3" />{deal.ownerUserId}</p> : null}{!readOnly ? <div className="mt-3 flex gap-2 border-t pt-3"><Select value={selectedStage} onValueChange={(value) => setSelectedStage(value as DealStage)}><SelectTrigger aria-label={`Move ${deal.name} to stage`} className="h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent>{DEAL_STAGES.map((stage) => <SelectItem key={stage} value={stage}>{DEAL_STAGE_LABELS[stage]}</SelectItem>)}</SelectContent></Select><Button size="sm" variant="outline" className="h-8 px-2 text-xs" disabled={selectedStage === deal.stage} onClick={() => move(deal, selectedStage)}>Move</Button></div> : null}</article>; }

export function DealsPipeline({ initialBoard, initialTotals, readOnly }: { initialBoard: Board; initialTotals: Record<DealStage, { count: number; valueCents: number }>; readOnly: boolean }) { const [board, setBoard] = useState(initialBoard); const [totals, setTotals] = useState(initialTotals); const [pendingLost, setPendingLost] = useState<{ deal: PipelineDeal; stage: DealStage } | null>(null); const [lostReason, setLostReason] = useState(""); const [moving, startTransition] = useTransition(); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }), useSensor(KeyboardSensor));
  const move = (deal: PipelineDeal, stage: DealStage, reason?: string) => { if (moving || stage === deal.stage) return; if (stage === "lost" && !reason) { setPendingLost({ deal, stage }); setLostReason(""); return; } const before = board; const beforeTotals = totals; const next = Object.fromEntries(DEAL_STAGES.map((name) => [name, board[name].filter((entry) => entry.id !== deal.id)])) as Board; const moved = { ...deal, stage }; next[stage] = [...next[stage], moved]; const nextTotals = Object.fromEntries(DEAL_STAGES.map((name) => [name, { count: next[name].length, valueCents: next[name].reduce((sum, entry) => sum + entry.valueCents, 0) }])) as typeof totals; setBoard(next); setTotals(nextTotals); startTransition(async () => { const result = await moveDealAction({ dealId: deal.id, stage, updatedAt: deal.updatedAt, lostReason: reason }); if (!result.success) { setBoard(before); setTotals(beforeTotals); toast.error(result.message); return; } setBoard((current) => ({ ...current, [stage]: current[stage].map((entry) => entry.id === deal.id ? { ...entry, updatedAt: result.updatedAt, lostReason: stage === "lost" ? reason ?? null : null } : entry) })); toast.success(result.message); }); };
  return <><DndContext sensors={sensors} onDragEnd={({ active, over }) => { const deal = Object.values(board).flat().find((entry) => entry.id === active.id); if (deal && over && DEAL_STAGES.includes(String(over.id) as DealStage)) move(deal, String(over.id) as DealStage); }}><div className="overflow-x-auto pb-3"><div className="flex min-w-max gap-4">{DEAL_STAGES.map((stage) => <Column key={stage} stage={stage} total={totals[stage]}>{board[stage].length ? board[stage].map((deal) => <DealCard key={deal.id} deal={deal} readOnly={readOnly} move={move} />) : <p className="rounded-2xl border border-dashed bg-background/60 p-4 text-center text-sm text-muted-foreground">Drop deals here</p>}</Column>)}</div></div></DndContext>{pendingLost ? <div role="dialog" aria-modal="true" aria-labelledby="lost-title" className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl border bg-background p-6 shadow-xl"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-500" /><h2 id="lost-title" className="font-semibold">Mark deal as lost</h2></div><p className="mt-2 text-sm text-muted-foreground">Capture why {pendingLost.deal.name} was lost before closing it.</p><Label className="mt-5 block" htmlFor="lostReason">Lost reason *</Label><Input id="lostReason" value={lostReason} onChange={(event) => setLostReason(event.target.value)} className="mt-2" autoFocus /><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={() => setPendingLost(null)} disabled={moving}>Cancel</Button><Button disabled={!lostReason.trim() || moving} onClick={() => { const pending = pendingLost; setPendingLost(null); move(pending.deal, pending.stage, lostReason.trim()); }}>Confirm lost</Button></div></div></div> : null}</>; }
