var R=require("./chunks/[turbopack]_runtime.js")("server/middleware.js")
R.c("server/chunks/node_modules_next_headers_0babr9-.js")
R.c("server/chunks/node_modules_next_1llih4q._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_0ptj_ys._.js")
R.c("server/chunks/node_modules_@clerk_shared_dist_0g-f-oi._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_1jnp-5n._.js")
R.c("server/chunks/node_modules_@clerk_nextjs_dist_esm_13fzne8._.js")
R.c("server/chunks/[root-of-the-server]__0suvdfy._.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/middleware.js { INNER_MIDDLEWARE_MODULE => \"[project]/proxy.ts [middleware] (ecmascript)\" } [middleware] (ecmascript)").exports
