// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/dashboard/accounts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/accounts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/activity">> = Specific
  const handler = {} as typeof import("../../app/dashboard/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/contacts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contacts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/contacts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/contacts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/contacts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/contacts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contacts/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/contacts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contacts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/accounts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/accounts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/accounts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/accounts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/accounts/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/accounts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/accounts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/accounts/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/accounts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/accounts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/contacts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/contacts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/contacts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/contacts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/contacts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/contacts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/contacts/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/contacts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers/contacts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/deals/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/deals/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/deals/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/deals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/deals/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/deals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/deals">> = Specific
  const handler = {} as typeof import("../../app/dashboard/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/import/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/import/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/import/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/import/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/import/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/import/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/import">> = Specific
  const handler = {} as typeof import("../../app/dashboard/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/leads/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/leads/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/leads/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/leads/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads">> = Specific
  const handler = {} as typeof import("../../app/dashboard/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/activity">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/audit-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/audit-log">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/audit-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/imports/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/imports/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/imports/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/imports/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/imports/history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/imports/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/imports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/imports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/imports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tasks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/invite/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[token]">> = Specific
  const handler = {} as typeof import("../../app/invite/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-in/[[...sign-in]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-in/[[...sign-in]]">> = Specific
  const handler = {} as typeof import("../../app/sign-in/[[...sign-in]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sign-up/[[...sign-up]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sign-up/[[...sign-up]]">> = Specific
  const handler = {} as typeof import("../../app/sign-up/[[...sign-up]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/demo-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/demo-login">> = Specific
  const handler = {} as typeof import("../../app/api/demo-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/[id]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/[id]/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/imports/[id]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/[id]/rejected/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/[id]/rejected">> = Specific
  const handler = {} as typeof import("../../app/api/imports/[id]/rejected/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/imports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports">> = Specific
  const handler = {} as typeof import("../../app/api/imports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/imports/templates/[entityType]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/imports/templates/[entityType]">> = Specific
  const handler = {} as typeof import("../../app/api/imports/templates/[entityType]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/export">> = Specific
  const handler = {} as typeof import("../../app/api/leads/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/testing/e2e/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testing/e2e/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/testing/e2e/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/testing/e2e/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/testing/e2e/reset">> = Specific
  const handler = {} as typeof import("../../app/api/testing/e2e/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/dashboard/customers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/customers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
