var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/imports/route.js")
R.c("server/chunks/[root-of-the-server]__1rf6y19._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_1p_mgx1._.js")
R.c("server/chunks/_1ei7yej._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_213iqqr._.js")
R.c("server/chunks/lib_arcjet_ts_1tgo8we._.js")
R.c("server/chunks/_1lgdzeq._.js")
R.c("server/chunks/_next-internal_server_app_api_imports_route_actions_0ky48tq.js")
R.m(83181)
module.exports=R.m(83181).exports
