import Link from "next/link";
import { notFound } from "next/navigation";
import { ExternalLink, Pencil, Plus } from "lucide-react";
import { getAccountDetails } from "@/app/dashboard/crm-queries";
import { ArchiveRecordButton } from "@/components/crm/archive-record-button";
import { DetailSection, EmptyRelationship } from "@/components/crm/detail-section";
import { PageHeader } from "@/components/dashboard/page-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { hasWorkspacePermission } from "@/lib/authorization";
import { DEAL_STAGE_LABELS } from "@/lib/constants/crm";
import { formatCurrencyFromCents } from "@/lib/revenue";
import { getCurrentWorkspace } from "@/lib/workspaces";

export default async function AccountDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const [data, workspace] = await Promise.all([getAccountDetails(id), getCurrentWorkspace()]); if (!data) notFound(); const canUpdate = hasWorkspacePermission(workspace.role, "crm:update_all") || hasWorkspacePermission(workspace.role, "crm:update_assigned"); const canDelete = hasWorkspacePermission(workspace.role, "crm:delete"); return <div className="space-y-5"><PageHeader eyebrow="Account" title={data.account.name} description={data.account.industry ?? "Company relationship and connected revenue context."} action={<div className="flex gap-2">{canUpdate ? <Button asChild variant="outline"><Link href={`/dashboard/customers/accounts/${id}/edit`}><Pencil className="mr-2 h-4 w-4" />Edit</Link></Button> : null}{canDelete ? <ArchiveRecordButton id={id} kind="account" /> : null}</div>} />
  <div className="grid gap-5 lg:grid-cols-3"><DetailSection title="Account details"><dl className="space-y-3 text-sm"><div><dt className="text-muted-foreground">Website</dt><dd>{data.account.website ? <a href={data.account.website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-medium text-primary">Visit website <ExternalLink className="h-3 w-3" /></a> : "—"}</dd></div><div><dt className="text-muted-foreground">Assigned owner</dt><dd>{data.account.assignedOwnerUserId ?? "Unassigned"}</dd></div><div><dt className="text-muted-foreground">Status</dt><dd><Badge variant={data.account.isArchived ? "secondary" : "default"}>{data.account.isArchived ? "Archived" : "Active"}</Badge></dd></div></dl></DetailSection><div className="space-y-5 lg:col-span-2"><DetailSection title="Contacts" action={canUpdate ? <Button asChild size="sm" variant="outline"><Link href={`/dashboard/customers/contacts/new?account=${id}`}><Plus className="mr-1 h-4 w-4" />Add contact</Link></Button> : undefined}>{data.relatedContacts.length ? <ul className="grid gap-3 sm:grid-cols-2">{data.relatedContacts.map((contact) => <li key={contact.id} className="rounded-2xl border p-3"><Link href={`/dashboard/customers/contacts/${contact.id}`} className="font-medium hover:text-primary">{contact.fullName}</Link>{contact.isPrimary ? <Badge className="ml-2" variant="secondary">Primary</Badge> : null}<p className="mt-1 text-sm text-muted-foreground">{contact.title ?? contact.email ?? "No role set"}</p></li>)}</ul> : <EmptyRelationship>No visible contacts are linked to this account.</EmptyRelationship>}</DetailSection>
  <DetailSection title="Pipeline"><div className="space-y-3">{data.relatedDeals.length ? data.relatedDeals.map((deal) => <div key={deal.id} className="flex items-center justify-between gap-3 rounded-2xl border p-3"><div><Link href={`/dashboard/deals/${deal.id}`} className="font-medium hover:text-primary">{deal.name}</Link><p className="text-sm text-muted-foreground">{DEAL_STAGE_LABELS[deal.stage]}{deal.expectedCloseAt ? ` · closes ${deal.expectedCloseAt.toLocaleDateString()}` : ""}</p></div><strong>{formatCurrencyFromCents(deal.valueCents, deal.currency)}</strong></div>) : <EmptyRelationship>No visible deals are linked to this account.</EmptyRelationship>}</div></DetailSection></div></div>
  <div className="grid gap-5 lg:grid-cols-2"><DetailSection title="Related leads">{data.relatedLeads.length ? <ul className="space-y-2">{data.relatedLeads.map((lead) => <li key={lead.id}><Link className="font-medium hover:text-primary" href={`/dashboard/leads/${lead.id}`}>{lead.fullName}</Link><span className="ml-2 text-sm text-muted-foreground">{lead.status}</span></li>)}</ul> : <EmptyRelationship>No visible leads are linked to this account.</EmptyRelationship>}</DetailSection><DetailSection title="Open tasks">{data.openTasks.length ? <ul className="space-y-2">{data.openTasks.map((task) => <li key={task.id} className="text-sm"><span className="font-medium">{task.title}</span><span className="ml-2 text-muted-foreground">{task.dueAt?.toLocaleDateString() ?? "No due date"}</span></li>)}</ul> : <EmptyRelationship>No open tasks are linked through this account&apos;s deals.</EmptyRelationship>}</DetailSection></div><DetailSection title="Recent activity">{data.events.length ? <ul className="space-y-3">{data.events.map((event) => <li key={event.id} className="border-l-2 pl-3 text-sm"><p>{event.message}</p><p className="mt-1 text-xs text-muted-foreground">{event.createdAt.toLocaleString()}</p></li>)}</ul> : <EmptyRelationship>No account activity yet.</EmptyRelationship>}</DetailSection></div>; }
